# Generated by Django 2.2 on 2019-04-07 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 12, 12, 15, 759896, tzinfo=utc)),
        ),
    ]
