# Generated by Django 2.2 on 2019-04-07 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20190407_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 12, 58, 41, 385669, tzinfo=utc)),
        ),
    ]
