# Generated by Django 2.2 on 2019-04-07 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190407_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 15, 49, 54, 565892, tzinfo=utc)),
        ),
    ]
