# Generated by Django 2.2 on 2019-04-08 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20190407_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=simditor.fields.RichTextField(verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 4, 47, 29, 688625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
    ]
