# Generated by Django 2.2 on 2019-04-08 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20190408_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=simditor.fields.RichTextField(blank=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 5, 2, 56, 225313, tzinfo=utc)),
        ),
    ]
