# Generated by Django 2.2 on 2019-04-08 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20190408_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=simditor.fields.RichTextField(verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 5, 32, 52, 419594, tzinfo=utc)),
        ),
    ]
