# Generated by Django 2.2 on 2019-04-08 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20190408_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_above', models.ImageField(blank=True, upload_to='article/%Y/%m/%d')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('article', simditor.fields.RichTextField(verbose_name='文章')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布')], default='draft', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 6, 48, 38, 377909, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='question.Article')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
